### ISSUE TITLE
Auto-detect input file measurement

### ISSUE THREAD

**Issue by lmperry** [flywheel-apps/mriqc#7]
Use input file's classification/metadata (if available) to determine measurement so the user does not have to select it. This will allow this gear to run automatically in many cases. 

Could have measurement options as such:
1. Auto-Detect (default)
2. Functional
3. T1w
4. T2w

**Comment by jenreiter** [comment]
@lmperry MRIQC currently checks to see if the filename is already in BIDS format. If it is, then we will determine the measurement from the BIDS filename. 

Should we still do this? Or should this only occur if 'auto-detect' is specified in the config file? Or more generally, what should be the order of precedence for determining the measurement? 

I'm currently implementing the following to determine the measurement but please feel free to suggest differently:

1. Check if filename is in BIDS, use this value for the measurement no matter what the config file says...
2. Check if config specifies 'auto-detect', try and auto-detect measurement, otherwise measurement is 'functional'
3. Check if config specifies measurement explicitly, use this value as the measurement
